x-default-env: &default-env
  environment:
    - PUID=1000
    - PGID=1000
    - UMASK=002
    - TZ=Asia/Kolkata

x-default-rest: &default-rest
  labels: 
    - "com.centurylinklabs.watchtower.enable=true"
  restart: unless-stopped

services:
  # Watchtower - Update all containers at 12pm every sunday
  watchtower:
    <<: *default-rest
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - TZ=Asia/Kolkata
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=* 0 12 * * 0	## S M H DOM M DOW
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  # Qbittorrent
  qbittorrent:
    <<: [*default-env, *default-rest]
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/qbittorrent:/config
      - /home/rpi/plex/data/torrents:/data/torrents

  # Plex
  plex:
    <<: [*default-env, *default-rest]
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
    environment:  
      - VERSION=docker
      - PLEX_CLAIM=claim-AawiosU4abC5Dj2pXHLE
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/plex:/config
      - /home/rpi/plex/data/media:/data/media

  # Flaresolverr - for 1337x
  flaresolverr:
    <<: *default-rest
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Kolkata

  # Prowlarr
  prowlarr:
    <<: [*default-env, *default-rest]
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      - flaresolverr
    ports:
      - "9696:9696"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/prowlarr:/config

  # Radarr
  radarr:
    <<: [*default-env, *default-rest]
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - qbittorrent
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/radarr:/config
      - /home/rpi/plex/data:/data

  # Sonarr
  sonarr:
    <<: [*default-env, *default-rest]
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - qbittorrent
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/rpi/plex/config/sonarr:/config
      - /home/rpi/plex/data:/data
