archive_tools="p7zip tar unrar unzip zip"
boot="efibootmgr grub os-prober"
browsers="firefox"
bt="alsa-utils bluez bluez-utils"
chat_apps="discord telegram-desktop"
download_tools="curl rclone wget yt-dlp"
env_tools="android-tools bc ccache clang docker fwupd libc++ nodejs npm sdl"
firewall="firewalld"
fs="dosfstools mtools squashfs-tools"
general="cups cups-browsed cups-pdf dialog gedit less libreoffice-fresh libusb-compat networkmanager repo sudo system-config-printer thunderbird tk vlc"
gpu_packages="amd-ucode mesa xf86-video-amdgpu"
ide="pycharm-community-edition"
kernel_firmware="linux linux-firmware linux-headers"
networking="net-tools"
ssh="openssh putty tigervnc tmate"
sys_info="htop fastfetch"
terminal_editors="nano vim"

pacman -S $archive_tools $boot $browsers $bt $chat_apps $download_tools $env_tools $firewall $fs $general $gpu_packages $ide $kernel_firmware $networking $ssh $sys_info $terminal_editors
