archive="p7zip tar unrar unzip zip"
boot="efibootmgr grub os-prober"
browser="firefox"
bt="alsa-firmware alsa-plugins alsa-utils bluez bluez-utils"
chat="discord telegram-desktop"
codecs="flac faac wavpack libmad opus libvorbis libwebp x265 libde265 x264 libmpeg2 libvpx"
download="curl rclone wget yt-dlp"
env="android-tools bc ccache clang docker docker-compose fwupd gcc gdb jdk17-openjdk libc++ nodejs npm sdl yarn"
firewall="firewalld"
fs="dosfstools mtools squashfs-tools"
general="dialog gedit gimp less libreoffice-still libusb-compat networkmanager obsidian obs-studio repo scrcpy sudo vlc"
gpu="amd-ucode mesa xf86-video-amdgpu"
ide="pycharm-community-edition"
kernel="linux linux-firmware linux-headers"
mpv="mpv mpv-mpris"
networking="inetutils iputils net-tools"
pipewire="pipewire pipewire-alsa pipewire-jack pipewire-pulse wireplumber"
printer="cups cups-browsed cups-filters cups-pdf system-config-printer"
py="python python-pip python-poetry"
ssh="openssh putty tigervnc tmate"
sys_info="htop fastfetch"
terminal_editors="nano vim"

pacman -S $archive $boot $browser $bt $chat $codecs $download $env $firewall $fs $general $gpu $ide $kernel $mpv $networking $pipewire $printer $py $ssh $sys_info $terminal_editors