archive="p7zip tar unrar unzip zip"
boot="efibootmgr grub os-prober"
browser="firefox"
bt="alsa-firmware alsa-plugins alsa-utils bluez bluez-libs bluez-utils"
chat="discord telegram-desktop"
codecs="flac faac wavpack libmad opus libvorbis libwebp x265 libde265 x264 libmpeg2 libvpx"
download="aria2 curl rclone wget yt-dlp"
env="android-tools bc clang docker docker-compose gcc gdb libc++ nodejs npm sdl yarn"
firewall="firewalld"
fonts="noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-dejavu ttf-liberation"
fs="dosfstools exfatprogs mtools squashfs-tools"
general="argon2 dialog dnsutils ffmpeg git iwd krita less libusb-compat networkmanager obs-studio qbittorrent reflector repo scrcpy sudo wpa_supplicant"
gpu="amd-ucode libva-mesa-driver mesa vulkan-radeon xf86-video-amdgpu"
kernel="linux-lts linux-firmware-amdgpu linux-firmware-other linux-firmware-radeon linux-firmware-realtek linux-lts-headers"
mpv="mpv mpv-mpris"
pipewire="pipewire pipewire-alsa pipewire-pulse wireplumber"
printer="cups cups-browsed cups-filters cups-pdf system-config-printer"
py="python python-pip python-ipykernel"
ssh="openssh putty tmate"
sys_info="fastfetch htop nload"
terminal_editors="gedit nano vim"

pacman -Syu --needed $archive $boot $browser $bt $chat $codecs $download $env $firewall $fonts $fs $general $gpu $kernel $mpv $pipewire $printer $py $ssh $sys_info $terminal_editors
