archive_tools="p7zip tar unrar unzip zip"
boot="efibootmgr grub os-prober"
browsers="firefox tor torbrowser-launcher"
bt="alsa-utils bluez bluez-utils"
chat_apps="discord telegram-desktop"
download_tools="curl rsync wget yt-dlp"
env_tools="android-tools bc ccache clang docker flatpak fwupd libc++ packagekit-qt5 python-pip python-pipx sdl"
firewall="gufw"
fs="dosfstools mtools squashfs-tools"
general="cups dialog gedit libreoffice-fresh libusb-compat lib32-mesa networkmanager optipng pngcrush repo sudo thunderbird tk vlc"
gpu_packages="amd-ucode mesa xf86-video-amdgpu"
ide="intellij-idea-community-edition pycharm-community-edition"
kernel_firmware="linux linux-firmware linux-headers"
networking="net-tools"
ssh="openssh tmate"
sys_info="htop neofetch"
terminal_editors="nano vim"

pacman -S $archive_tools $boot $browsers $bt $chat_apps $download_tools $env_tools $firewall $fs $general $gpu_packages $ide $kernel_firmware $networking $ssh $sys_info $terminal_editors
