archive_tools="p7zip tar unrar unzip zip"
boot="efibootmgr grub os-prober"
browsers="firefox tor torbrowser-launcher"
bt="alsa-utils bluez bluez-utils"
chat_apps="discord telegram-desktop"
docker="docker docker-buildx"
download_tools="curl rsync wget yt-dlp"
env_tools="android-tools bc ccache clang docker flatpak fwupd libc++ packagekit-qt5 sdl"
firewall="gufw"
fs="dosfstools mtools squashfs-tools"
general="cups dialog gedit libreoffice-fresh libusb-compat lib32-mesa networkmanager optipng pngcrush rclone repo sudo thunderbird tk vlc"
gpu_packages="amd-ucode mesa xf86-video-amdgpu"
ide="intellij-idea-community-edition pycharm-community-edition"
kernel_firmware="linux linux-firmware linux-headers"
networking="net-tools"
python="python python-google-api-python-client python-google-auth-oauthlib python-httplib2 python-oauth2client python-progressbar python-pip python-pipx"
ssh="openssh tmate"
sys_info="htop neofetch"
terminal_editors="nano vim"

pacman -S $archive_tools $boot $browsers $bt $chat_apps $docker $download_tools $env_tools $firewall $fs $general $gpu_packages $ide $kernel_firmware $networking $python $ssh $sys_info $terminal_editors
