ACCEPT_LICENSE="*"
CCACHE_DIR="/var/tmp/ccache"
CCACHE_SIZE="50G"
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
CHOST="x86_64-pc-linux-gnu"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORTAGE_TMPDIR="/tmp"

EMERGE_DEFAULT_OPTS="--ask"
USE_AUDIO="a52 aac alsa faad flac lyrics mp3 mp4 pulseaudio sound wav"
USE_CLI="cli ncurses aalib libcaca"
USE_COMPRESS="7zip archive bzip2 rar zip"
USE_FS="fat ntfs ext2 ext3 ext4"
USE_GFX="drm opengl plotutils sdl sdl2 svga vulkan"
USE_IMAGE="apng epub exif gif gimp gui jbig jpeg jpeg2k mng openexr pdf pdfimport png raw svg system-png thumbnail tiff"
USE_NETWORK="curl dhcpcd http iwd networkmanager resolvconf wifi wps"
USE_SECURITY="crypt firewall gcrypt"
USE_SYSTEM="acpi cups dbus display-manager git gtk modules multilib offensive policykit screen-sharing symlink touchpad"
USE_TEXT="fontconfig icu unicode xml"
USE_VIDEO="aalib css libcaca mp4 mpeg encode ncurses"
USE_WEB="sockets curl ftp"
USE="gnome -qt5 -kde bluetooth nvidia python ${USE_AUDIO} ${USE_CLI} ${USE_COMPRESS} ${USE_FS} ${USE_GFX} ${USE_IMAGE} ${USE_NETWORK} ${USE_SECURITY} ${USE_SYSTEM} ${USE_TEXT} ${USE_VIDEO} ${USE_WEB}"

GRUB_PLATFORMS="efi-64"

FEATURES="ccache parallel-fetch parallel-install splitdebug"
GENTOO_MIRRORS="https://mirrors.nxtgen.com/gentoo-mirror/gentoo-source/"

LC_MESSAGES=C
LINGUAS="en_US"

INPUT_DEVICES="keyboard mouse libinput evdev synaptics joystick"

MAKEOPTS="-j8"
VIDEO_CARDS="amdgpu radeonsi nvidia"
