ACCEPT_LICENSE="*"
CCACHE_DIR="/var/tmp/ccache"
CCACHE_SIZE="50G"
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
CHOST="x86_64-pc-linux-gnu"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"

PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORTAGE_TMPDIR="/tmp"

EMERGE_DEFAULT_OPTS="--ask"

GRUB_PLATFORMS="efi-64"

FEATURES="ccache parallel-fetch parallel-install splitdebug"
GENTOO_MIRRORS="https://mirrors.nxtgen.com/gentoo-mirror/gentoo-source/"

LC_MESSAGES=C
LINGUAS="en_US"

INPUT_DEVICES="keyboard mouse libinput evdev synaptics joystick"

MAKEOPTS="-j8"
VIDEO_CARDS="amdgpu radeonsi nvidia"
